window.products = [
  {
    id: "men-shirt-classic",
    name: "Эрэгтэй цамц",
    brand: "UNIQLO",
    categoryId: "men",
    categoryIds: ["men"],
    category: "Эрэгтэй",
    subcategoryId: "shirt",
    subcategoryIds: ["shirt"],
    subcategory: "Цамц",
    price: "99,000 ₮",
    oldPrice: "129,000 ₮",
    description: "Өдөр тутам болон ажил хэрэгт өмсөх сонгодог эрэгтэй цамц.",
    size: "L",
    image: "pictures/shirt-card.svg",
    colorA: "#bfdbfe",
    colorB: "#2563eb",
    initials: "SHIRT",
    tags: ["эрэгтэй", "цамц", "shirt", "formal"],
  },
  {
    id: "men-pants-slim",
    name: "Slim өмд",
    brand: "ZARA",
    categoryId: "men",
    categoryIds: ["men"],
    category: "Эрэгтэй",
    subcategoryId: "pants",
    subcategoryIds: ["pants"],
    subcategory: "Өмд",
    price: "119,000 ₮",
    oldPrice: "149,000 ₮",
    description: "Хотын өдөр тутмын хэрэглээнд тохирох slim загварын өмд.",
    size: "32",
    image: "pictures/shirt-card.svg",
    colorA: "#d1d5db",
    colorB: "#4b5563",
    initials: "PANTS",
    tags: ["эрэгтэй", "өмд", "pants"],
  },
  {
    id: "men-shoes-vans",
    name: "Кет",
    brand: "VANS",
    categoryId: "men",
    categoryIds: ["men"],
    category: "Эрэгтэй",
    subcategoryId: "shoes",
    subcategoryIds: ["shoes", "sneaker"],
    subcategory: "Гутал",
    price: "159,000 ₮",
    oldPrice: "189,000 ₮",
    description: "Өдөр тутмын эвтэйхэн кет.",
    size: "42",
    image: "pictures/sneaker-card.svg",
    colorA: "#e5e7eb",
    colorB: "#6b7280",
    initials: "VANS",
    tags: ["кет", "гутал", "эрэгтэй", "sneaker"],
  },
  {
    id: "women-dress-zara",
    name: "Даашинз",
    brand: "ZARA",
    categoryId: "women",
    categoryIds: ["women"],
    category: "Эмэгтэй",
    subcategoryId: "dress",
    subcategoryIds: ["dress"],
    subcategory: "Даашинз",
    price: "149,000 ₮",
    oldPrice: "179,000 ₮",
    description: "Гоёлын болон өдөр тутмын даашинз.",
    size: "M",
    image: "pictures/dress-card.svg",
    colorA: "#fecdd3",
    colorB: "#fb7185",
    initials: "DRESS",
    tags: ["даашинз", "эмэгтэй", "dress"],
  },
  {
    id: "women-bag-charles",
    name: "Гар цүнх",
    brand: "CHARLES & KEITH",
    categoryId: "women",
    categoryIds: ["women"],
    category: "Эмэгтэй",
    subcategoryId: "bag",
    subcategoryIds: ["bag"],
    subcategory: "Цүнх",
    price: "210,000 ₮",
    oldPrice: "245,000 ₮",
    description: "Гар цүнх болон мөрний цүнх.",
    size: "One size",
    image: "pictures/bag-card.svg",
    colorA: "#cbd5e1",
    colorB: "#475569",
    initials: "BAG",
    tags: ["цүнх", "bag", "эмэгтэй"],
  },
  {
    id: "women-outerwear-coat",
    name: "Пальто",
    brand: "LIU JO",
    categoryId: "women",
    categoryIds: ["women"],
    category: "Эмэгтэй",
    subcategoryId: "outerwear",
    subcategoryIds: ["outerwear", "coat"],
    subcategory: "Гадуур хувцас",
    price: "329,000 ₮",
    oldPrice: "379,000 ₮",
    description: "Өвлийн эмэгтэй пальто.",
    size: "M",
    image: "pictures/coat-card.svg",
    colorA: "#f5d0fe",
    colorB: "#c084fc",
    initials: "COAT",
    tags: ["эмэгтэй", "пальто", "гадуур хувцас", "coat"],
  },
  {
    id: "women-makeup-palette",
    name: "Нүдний будгийн палет",
    brand: "HUDA",
    categoryId: "women",
    categoryIds: ["women", "cosmetics"],
    category: "Эмэгтэй",
    subcategoryId: "makeup",
    subcategoryIds: ["makeup"],
    subcategory: "Нүүр будалт",
    price: "125,000 ₮",
    oldPrice: "155,000 ₮",
    description: "Олон өнгийн будгийн палет.",
    size: "12 өнгө",
    image: "pictures/palette-card.svg",
    colorA: "#fef3c7",
    colorB: "#f97316",
    initials: "HUDA",
    tags: ["палет", "будгийн палет", "гоо сайхан", "makeup"],
  },
  {
    id: "tech-phone-xiaomi",
    name: "Ухаалаг утас",
    brand: "XIAOMI",
    categoryId: "tech",
    categoryIds: ["tech", "electronics"],
    category: "Технологи",
    subcategoryId: "phone",
    subcategoryIds: ["phone"],
    subcategory: "Гар утас",
    price: "899,000 ₮",
    oldPrice: "999,000 ₮",
    description: "Өдөр тутмын хэрэглээнд хурдан, багтаамж сайтай гар утас.",
    size: "128GB",
    image: "pictures/smartwatch-card.svg",
    colorA: "#dbeafe",
    colorB: "#1d4ed8",
    initials: "PHONE",
    tags: ["гар утас", "phone", "технологи", "электрон бараа"],
  },
  {
    id: "tech-laptop-lenovo",
    name: "Laptop",
    brand: "LENOVO",
    categoryId: "tech",
    categoryIds: ["tech", "electronics"],
    category: "Технологи",
    subcategoryId: "laptop",
    subcategoryIds: ["laptop"],
    subcategory: "Laptop",
    price: "2,490,000 ₮",
    oldPrice: "2,790,000 ₮",
    description: "Суралцах, ажиллахад тохиромжтой зөөврийн компьютер.",
    size: "14 inch",
    image: "pictures/smartwatch-card.svg",
    colorA: "#e0e7ff",
    colorB: "#4338ca",
    initials: "LAPTOP",
    tags: ["laptop", "зөөврийн компьютер", "технологи"],
  },
  {
    id: "tech-headphones-sony",
    name: "Чихэвч",
    brand: "SONY",
    categoryId: "tech",
    categoryIds: ["tech", "electronics"],
    category: "Технологи",
    subcategoryId: "headphones",
    subcategoryIds: ["headphones"],
    subcategory: "Чихэвч",
    price: "299,000 ₮",
    oldPrice: "349,000 ₮",
    description: "Дуу тусгаарлалттай wireless чихэвч.",
    size: "Wireless",
    image: "pictures/smartwatch-card.svg",
    colorA: "#cffafe",
    colorB: "#0891b2",
    initials: "AUDIO",
    tags: ["чихэвч", "headphones", "audio"],
  },
  {
    id: "kids-toy-blocks",
    name: "Угсардаг тоглоом",
    brand: "LEGO",
    categoryId: "kids",
    categoryIds: ["kids"],
    category: "Хүүхдийн",
    subcategoryId: "toy",
    subcategoryIds: ["toy"],
    subcategory: "Тоглоом",
    price: "89,000 ₮",
    oldPrice: "109,000 ₮",
    description: "Бүтээлч сэтгэлгээг хөгжүүлэх угсардаг тоглоом.",
    size: "120 pcs",
    image: "pictures/palette-card.svg",
    colorA: "#fde68a",
    colorB: "#f59e0b",
    initials: "TOY",
    tags: ["хүүхдийн", "тоглоом", "toy"],
  },
  {
    id: "kids-clothes-shirt",
    name: "Хүүхдийн футболка",
    brand: "CARTER'S",
    categoryId: "kids",
    categoryIds: ["kids"],
    category: "Хүүхдийн",
    subcategoryId: "clothes",
    subcategoryIds: ["clothes"],
    subcategory: "Хувцас",
    price: "39,000 ₮",
    oldPrice: "49,000 ₮",
    description: "Зөөлөн даавуун хүүхдийн футболка.",
    size: "6-7Y",
    image: "pictures/shirt-card.svg",
    colorA: "#d1fae5",
    colorB: "#10b981",
    initials: "KIDS",
    tags: ["хүүхдийн", "хувцас", "футболка"],
  },
  {
    id: "home-frame-basic",
    name: "Зургийн хүрээ",
    brand: "HUSUG",
    categoryId: "home",
    categoryIds: ["home", "household"],
    category: "Гэрийн тавилга",
    subcategoryId: "frame",
    subcategoryIds: ["frame"],
    subcategory: "Хүрээ",
    price: "35,000 ₮",
    oldPrice: "45,000 ₮",
    description: "Интерьер чимэх минимал зургийн хүрээ.",
    size: "A4",
    image: "pictures/tablecloth-card.svg",
    colorA: "#f3f4f6",
    colorB: "#9ca3af",
    initials: "FRAME",
    tags: ["гэрийн тавилга", "хүрээ", "frame"],
  },
  {
    id: "home-tablecloth",
    name: "Ширээний бүтээлэг",
    brand: "HUSUG",
    categoryId: "home",
    categoryIds: ["home", "household"],
    category: "Гэрийн тавилга",
    subcategoryId: "household",
    subcategoryIds: ["household"],
    subcategory: "Гэр ахуйн бараа",
    price: "77,000 ₮",
    oldPrice: "95,000 ₮",
    description: "Гэрийн интерьерийн ширээний бүтээлэг.",
    size: "150x220",
    image: "pictures/tablecloth-card.svg",
    colorA: "#f3f4f6",
    colorB: "#d1d5db",
    initials: "HOME",
    tags: ["ширээний бүтээлэг", "гэр ахуй", "household"],
  },
  {
    id: "home-diffuser",
    name: "Diffuser",
    brand: "HUSUG",
    categoryId: "household",
    categoryIds: ["household", "home"],
    category: "Гэр ахуйн бараа",
    subcategoryId: "household",
    subcategoryIds: ["household", "skincare"],
    subcategory: "Гэр ахуйн бараа",
    price: "99,000 ₮",
    oldPrice: "119,000 ₮",
    description: "Өрөөний үнэртүүлэгч diffuser.",
    size: "Standard",
    image: "pictures/diffuser-card.svg",
    colorA: "#fae8ff",
    colorB: "#d946ef",
    initials: "AROMA",
    tags: ["diffuser", "үнэртүүлэгч", "гэр ахуй"],
  },
  {
    id: "cosmetics-lipstick-mac",
    name: "Уруулын будаг",
    brand: "MAC",
    categoryId: "cosmetics",
    categoryIds: ["cosmetics", "women"],
    category: "Гоо сайхан",
    subcategoryId: "makeup",
    subcategoryIds: ["makeup"],
    subcategory: "Нүүр будалт",
    price: "58,000 ₮",
    oldPrice: "75,000 ₮",
    description: "Тод өнгийн уруулын будаг.",
    size: "3.5g",
    image: "pictures/lipstick-card.svg",
    colorA: "#fecdd3",
    colorB: "#e11d48",
    initials: "MAC",
    tags: ["уруулын будаг", "гоо сайхан", "lipstick", "makeup"],
  },
  {
    id: "cosmetics-skincare-cleanser",
    name: "Арьс цэвэрлэгч",
    brand: "COSRX",
    categoryId: "cosmetics",
    categoryIds: ["cosmetics"],
    category: "Гоо сайхан",
    subcategoryId: "skincare",
    subcategoryIds: ["skincare"],
    subcategory: "Арьс арчилгаа",
    price: "42,000 ₮",
    oldPrice: "52,000 ₮",
    description: "Өдөр тутмын зөөлөн цэвэрлэгч.",
    size: "150ml",
    image: "pictures/lipstick-card.svg",
    colorA: "#dcfce7",
    colorB: "#22c55e",
    initials: "SKIN",
    tags: ["арьс арчилгаа", "цэвэрлэгч", "skincare"],
  },
];

window.productData = window.products;
