window.SHOPPY_DATA = {
  categories: [
    {
      id: "women",
      name: "Эмэгтэй",
      description: "Өдөр тутам, оффис болон онцгой мөчид тохирох эмэгтэй коллекц.",
      subcategories: [
        { id: "dress", name: "Даашинз" },
        { id: "bag", name: "Цүнх" },
        { id: "shoes", name: "Гутал" },
        { id: "outerwear", name: "Гадуур хувцас" },
        { id: "jewelry", name: "Гоёл чимэглэл" },
        { id: "makeup", name: "Нүүр будалт" }
      ]
    },
    {
      id: "men",
      name: "Эрэгтэй",
      description: "Ажил, спорт, чөлөөт цагт зориулсан эрэгтэй бараанууд.",
      subcategories: [
        { id: "shirt", name: "Цамц" },
        { id: "pants", name: "Өмд" },
        { id: "shoes", name: "Гутал" }
      ]
    },
    {
      id: "tech",
      name: "Технологи",
      description: "Өдөр тутмын хэрэглээнд зориулагдсан ухаалаг төхөөрөмжүүд.",
      subcategories: [
        { id: "phone", name: "Гар утас" },
        { id: "laptop", name: "Laptop" },
        { id: "headphones", name: "Чихэвч" }
      ]
    },
    {
      id: "kids",
      name: "Хүүхдийн",
      description: "Хүүхдийн тоглоом, хувцас, гутлын сонголтууд.",
      subcategories: [
        { id: "toy", name: "Тоглоом" },
        { id: "clothes", name: "Хувцас" },
        { id: "shoes", name: "Гутал" }
      ]
    },
    {
      id: "home",
      name: "Гэрийн тавилга",
      description: "Интерьерээ илүү дулаан, эмх цэгцтэй болгох шийдлүүд.",
      subcategories: [
        { id: "frame", name: "Хүрээ" },
        { id: "furniture", name: "Тавилга" },
        { id: "household", name: "Гэр ахуйн бараа" }
      ]
    },
    {
      id: "electronics",
      name: "Электрон бараа",
      description: "Ажил, зугаа цэнгэл, хөдөлгөөнд зориулагдсан электроник бараанууд.",
      subcategories: [
        { id: "phone", name: "Гар утас" },
        { id: "laptop", name: "Laptop" },
        { id: "headphones", name: "Чихэвч" }
      ]
    },
    {
      id: "cosmetics",
      name: "Гоо сайхан",
      description: "Арьс арчилгаа, будалт, өдөр тутмын гоо сайхны багц.",
      subcategories: [
        { id: "makeup", name: "Нүүр будалт" },
        { id: "skincare", name: "Арьс арчилгаа" }
      ]
    },
    {
      id: "household",
      name: "Гэр ахуйн бараа",
      description: "Гэр ахуй, хадгалалт, тохижилтод зориулсан бараанууд.",
      subcategories: [
        { id: "frame", name: "Хүрээ" },
        { id: "furniture", name: "Тавилга" },
        { id: "household", name: "Гэр ахуйн бараа" }
      ]
    }
  ],
  products: [
    {
      id: "women-jacket-liujo",
      category: "women",
      subcategory: "outerwear",
      name: "LIU JO Quilted Jacket",
      brand: "LIU JO",
      price: 329000,
      oldPrice: 389000,
      badge: "-15%",
      rating: 4.8,
      reviews: 61,
      imageLabel: "LIU JO",
      imageTone: "linear-gradient(135deg, #c9d6e5, #6d7a8d)",
      shortDescription: "Салхи, сэрүүн өдөрт тохирох бүстэй, хөнгөн дулаан хүрэм.",
      description: "Хотын хэмнэлд зохицох минимал хийцтэй, бүстэй эмэгтэй хүрэм. Өдөр тутмын denim, boots-той амархан хослоно.",
      details: ["Бүстэй силуэт", "Хөнгөн дулаалга", "Дотор зөөлөн lining", "Улирлын шинэ загвар"],
      sizes: ["S", "M", "L"],
      colors: ["Хар", "Саарал"],
      featured: true
    },
    {
      id: "women-city-bag",
      category: "women",
      subcategory: "bag",
      name: "City Soft Tote Bag",
      brand: "Mysa",
      price: 189000,
      oldPrice: 219000,
      badge: "Шинэ",
      rating: 4.7,
      reviews: 28,
      imageLabel: "TOTE",
      imageTone: "linear-gradient(135deg, #efd4c2, #c18e73)",
      shortDescription: "Өдөр бүр хэрэглэхэд хөнгөн, багтаамжтай tote цүнх.",
      description: "Ноутбук, гоо сайхны цүнх, тэмдэглэлийн дэвтэр гээд өдөр тутмын хэрэгцээг цэгцтэй авч явахад зориулсан зөөлөн tote цүнх.",
      details: ["Дотор 3 тасалгаа", "Мөрөнд эвтэйхэн", "Хиймэл арьсан материал", "Ажлын өдөрт тохиромжтой"],
      sizes: ["One size"],
      colors: ["Tan", "Cream"],
      featured: true
    },
    {
      id: "women-satin-dress",
      category: "women",
      subcategory: "dress",
      name: "Satin Evening Dress",
      brand: "Sora",
      price: 259000,
      oldPrice: 299000,
      badge: "-13%",
      rating: 4.9,
      reviews: 45,
      imageLabel: "DRESS",
      imageTone: "linear-gradient(135deg, #f8d6cf, #c76f6f)",
      shortDescription: "Төрөл бүрийн арга хэмжээнд өмсөх торгомсог даашинз.",
      description: "Биеийн шугамыг зөөлөн тодотгох торгомсог материалтай, оройн зоог болон хүндэтгэлийн арга хэмжээнд тохирох даашинз.",
      details: ["Сатин материал", "Нурууны hidden zip", "Mid-length загвар"],
      sizes: ["S", "M", "L"],
      colors: ["Rose", "Black"]
    },
    {
      id: "men-oxford-shirt",
      category: "men",
      subcategory: "shirt",
      name: "Oxford Classic Shirt",
      brand: "North Thread",
      price: 129000,
      oldPrice: 149000,
      badge: "-13%",
      rating: 4.6,
      reviews: 24,
      imageLabel: "SHIRT",
      imageTone: "linear-gradient(135deg, #d7e3f0, #87a3c1)",
      shortDescription: "Оффис болон casual хослолд зохицох классик цамц.",
      description: "Амьсгалдаг хөвөн даавуун материалтай, оффисын болон чөлөөт стилийн аль алинд нь тохирох эрэгтэй цамц.",
      details: ["100% cotton", "Regular fit", "Wrinkle resistant finish"],
      sizes: ["M", "L", "XL"],
      colors: ["White", "Sky blue"],
      featured: true
    },
    {
      id: "men-wide-pants",
      category: "men",
      subcategory: "pants",
      name: "Urban Straight Pants",
      brand: "Axis",
      price: 149000,
      oldPrice: 179000,
      badge: "Онцлох",
      rating: 4.5,
      reviews: 19,
      imageLabel: "PANTS",
      imageTone: "linear-gradient(135deg, #d9d0c8, #8a7568)",
      shortDescription: "Өдөр тутмын хөдөлгөөнд эвтэйхэн straight fit өмд.",
      description: "Стрит хэв маягтай, халаасны цэвэр шийдэлтэй, sneaker болон loafer-тэй амархан зохицох өмд.",
      details: ["Straight fit", "Stretch даавуу", "Side pocket detail"],
      sizes: ["M", "L", "XL"],
      colors: ["Stone", "Black"]
    },
    {
      id: "men-runner-shoes",
      category: "men",
      subcategory: "shoes",
      name: "Velocity Runner",
      brand: "Peak Motion",
      price: 219000,
      oldPrice: 249000,
      badge: "-12%",
      rating: 4.8,
      reviews: 37,
      imageLabel: "RUN",
      imageTone: "linear-gradient(135deg, #2a3d4d, #7f9ab0)",
      shortDescription: "Өдөр тутам болон алхалтад тохирсон хөнгөн пүүз.",
      description: "Хөнгөн ултай, амьсгалдаг mesh материалтай тул бүтэн өдрийн хөдөлгөөнд эвтэйхэн мэдрэмж өгнө.",
      details: ["Breathable mesh", "Cushion sole", "Everyday comfort"],
      sizes: ["40", "41", "42", "43"],
      colors: ["Black", "Navy"]
    },
    {
      id: "tech-flagship-phone",
      category: "tech",
      subcategory: "phone",
      name: "Nova X Pro 256GB",
      brand: "Nova",
      price: 2499000,
      oldPrice: 2699000,
      badge: "5G",
      rating: 4.9,
      reviews: 82,
      imageLabel: "NOVA",
      imageTone: "linear-gradient(135deg, #dbe9ff, #6785c1)",
      shortDescription: "Өндөр гүйцэтгэлтэй камер, урт цэнэгтэй ухаалаг утас.",
      description: "50MP камер, 120Hz дэлгэц, өдөржин ашиглах баттерейтай премиум ангиллын ухаалаг утас.",
      details: ["120Hz AMOLED", "50MP main camera", "Fast charge", "256GB storage"],
      sizes: ["256GB"],
      colors: ["Blue", "Graphite"],
      featured: true
    },
    {
      id: "tech-slim-laptop",
      category: "tech",
      subcategory: "laptop",
      name: "AirBook 14",
      brand: "Aster",
      price: 3199000,
      oldPrice: 3499000,
      badge: "-9%",
      rating: 4.7,
      reviews: 34,
      imageLabel: "14",
      imageTone: "linear-gradient(135deg, #f3f5f8, #9da6b2)",
      shortDescription: "Хичээл, ажил, аялалд авч явахад хөнгөн laptop.",
      description: "14 инчийн IPS дэлгэц, SSD хадгалалт, урт battery life бүхий slim загварын laptop.",
      details: ["14-inch IPS", "16GB RAM", "512GB SSD", "1.3kg weight"],
      sizes: ["14-inch"],
      colors: ["Silver"]
    },
    {
      id: "tech-noise-headphones",
      category: "tech",
      subcategory: "headphones",
      name: "Noise Cancel Headphones",
      brand: "Wave",
      price: 359000,
      oldPrice: 399000,
      badge: "ANC",
      rating: 4.8,
      reviews: 56,
      imageLabel: "ANC",
      imageTone: "linear-gradient(135deg, #d6d8dc, #59606b)",
      shortDescription: "Ажлын төвлөрөл, аялалд зориулсан noise cancel чихэвч.",
      description: "Идэвхтэй дуу тусгаарлалттай тул оффис, онгоц, кофе шопын орчинд ч төвлөрөхөд тусална.",
      details: ["40h battery", "Bluetooth 5.3", "ANC", "Comfort earcups"],
      sizes: ["One size"],
      colors: ["Black", "Silver"],
      featured: true
    },
    {
      id: "kids-robot-toy",
      category: "kids",
      subcategory: "toy",
      name: "Robo Builder Set",
      brand: "PlayBox",
      price: 89000,
      oldPrice: 109000,
      badge: "-18%",
      rating: 4.9,
      reviews: 48,
      imageLabel: "ROBO",
      imageTone: "linear-gradient(135deg, #ffe9aa, #ff9d5c)",
      shortDescription: "Сэтгэн бодох чадвар хөгжүүлэх робот угсрах тоглоом.",
      description: "Хүүхдийн логик сэтгэлгээ, гарын эв дүйг хөгжүүлэх зориулалттай олон хэсгээс бүрдсэн тоглоомын багц.",
      details: ["6+ нас", "120 pieces", "STEM learning"],
      sizes: ["6+"],
      colors: ["Multi"]
    },
    {
      id: "kids-soft-set",
      category: "kids",
      subcategory: "clothes",
      name: "Soft Cotton Set",
      brand: "MiniMood",
      price: 99000,
      oldPrice: 119000,
      badge: "New",
      rating: 4.7,
      reviews: 21,
      imageLabel: "KID",
      imageTone: "linear-gradient(135deg, #d9f1ff, #8fb7cf)",
      shortDescription: "Өдөр тутмын хөдөлгөөнд эвтэйхэн хүүхдийн хослол.",
      description: "Зөөлөн хөвөн материалтай, угаахад арчилгаа багатай, өдөр тутам өмсөхөд тохиромжтой хувцасны сет.",
      details: ["Cotton blend", "Easy wash", "Comfort fit"],
      sizes: ["110", "120", "130"],
      colors: ["Blue", "Pink"]
    },
    {
      id: "home-wood-frame",
      category: "home",
      subcategory: "frame",
      name: "Oak Gallery Frame",
      brand: "Nest",
      price: 69000,
      oldPrice: 79000,
      badge: "Set",
      rating: 4.6,
      reviews: 14,
      imageLabel: "FRAME",
      imageTone: "linear-gradient(135deg, #f0ddcc, #b58f70)",
      shortDescription: "Зураг, постероо хүрээлэх дулаан модон хүрээ.",
      description: "Орчин үеийн интерьер болон минимал ханын чимэглэлд тохирох байгалийн өнгөтэй frame.",
      details: ["Natural oak finish", "Wall mount ready", "A3 size"],
      sizes: ["A3"],
      colors: ["Oak"]
    },
    {
      id: "home-lounge-chair",
      category: "home",
      subcategory: "furniture",
      name: "Nordic Lounge Chair",
      brand: "Oakroom",
      price: 429000,
      oldPrice: 499000,
      badge: "-14%",
      rating: 4.8,
      reviews: 17,
      imageLabel: "CHAIR",
      imageTone: "linear-gradient(135deg, #efe4d6, #a78d73)",
      shortDescription: "Унших буланд төгс зохицох зөөлөн түшлэгтэй сандал.",
      description: "Зочны өрөө, унтлагын өрөөний буланд тухтай орон зай бүрдүүлэх Nordic хэв маягийн түшлэгтэй сандал.",
      details: ["Wood legs", "Soft linen fabric", "Easy assembly"],
      sizes: ["One size"],
      colors: ["Beige", "Olive"],
      featured: true
    },
    {
      id: "electronics-smart-watch",
      category: "electronics",
      subcategory: "phone",
      name: "Pulse Smart Watch",
      brand: "Orbit",
      price: 459000,
      oldPrice: 499000,
      badge: "New",
      rating: 4.7,
      reviews: 29,
      imageLabel: "PULSE",
      imageTone: "linear-gradient(135deg, #ecf1f8, #7c8795)",
      shortDescription: "Дасгал, мэдэгдэл, зүрхний хэмийг хянах smart watch.",
      description: "Өдөр тутмын алхам, нойр, зүрхний цохилтоо хянах, утасны мэдэгдэл хүлээн авах ухаалаг цаг.",
      details: ["AMOLED display", "7-day battery", "Water resistant"],
      sizes: ["42mm"],
      colors: ["Black", "Champagne"]
    },
    {
      id: "electronics-gamer-laptop",
      category: "electronics",
      subcategory: "laptop",
      name: "Vortex Gaming 15",
      brand: "Vortex",
      price: 4299000,
      oldPrice: 4599000,
      badge: "RTX",
      rating: 4.8,
      reviews: 26,
      imageLabel: "RTX",
      imageTone: "linear-gradient(135deg, #10151c, #2b5072)",
      shortDescription: "Тоглоом болон видео edit-д зориулсан өндөр хүчин чадалтай laptop.",
      description: "Discrete graphics, high refresh дэлгэц, dual fan cooling системтэй performance laptop.",
      details: ["15.6-inch 144Hz", "RTX graphics", "1TB SSD", "RGB keyboard"],
      sizes: ["15.6-inch"],
      colors: ["Black"]
    },
    {
      id: "cosmetics-skin-set",
      category: "cosmetics",
      subcategory: "skincare",
      name: "Hydra Skin Routine Set",
      brand: "Derm Lab",
      price: 139000,
      oldPrice: 169000,
      badge: "Set",
      rating: 4.9,
      reviews: 73,
      imageLabel: "SKIN",
      imageTone: "linear-gradient(135deg, #fbe7ee, #d8a7bc)",
      shortDescription: "Арьс чийгшүүлэх гурван алхамтай арчилгааны багц.",
      description: "Өглөө, оройн арчилгаанд тохирох cleanser, serum, cream багтсан skin routine сет.",
      details: ["Cleanser + Serum + Cream", "Sensitive skin friendly", "Daily use"],
      sizes: ["3 pcs"],
      colors: ["Rose"]
    },
    {
      id: "cosmetics-lip-kit",
      category: "cosmetics",
      subcategory: "makeup",
      name: "Velvet Lip Kit",
      brand: "Muse",
      price: 79000,
      oldPrice: 95000,
      badge: "-17%",
      rating: 4.6,
      reviews: 41,
      imageLabel: "LIP",
      imageTone: "linear-gradient(135deg, #ffd8dd, #d36a7a)",
      shortDescription: "Өдөр тутмын болон үдэшлэгийн будалтад тохирох lip set.",
      description: "Матт болон satin finish бүхий 4 өнгийн lip багц. Өдөр тутмын neutral, evening bold өнгө хоёул орсон.",
      details: ["4 shades", "Long wear", "Soft finish"],
      sizes: ["4 pcs"],
      colors: ["Rose", "Brick", "Nude"]
    },
    {
      id: "household-storage-box",
      category: "household",
      subcategory: "household",
      name: "Stack Storage Box",
      brand: "Homey",
      price: 59000,
      oldPrice: 69000,
      badge: "-14%",
      rating: 4.5,
      reviews: 18,
      imageLabel: "BOX",
      imageTone: "linear-gradient(135deg, #e6e5e1, #9b988f)",
      shortDescription: "Шүүгээ, тавиурт цэгцтэй хадгалах олон зориулалтын хайрцаг.",
      description: "Гэр ахуйн жижиг хэрэглэл, хүүхдийн тоглоом, бичиг хэрэг хадгалахад тохиромжтой stack хийцтэй storage box.",
      details: ["Lid included", "Stackable", "Easy clean"],
      sizes: ["Large"],
      colors: ["Ivory", "Grey"]
    }
  ],
  featuredProductIds: [
    "women-jacket-liujo",
    "tech-flagship-phone",
    "home-lounge-chair",
    "tech-noise-headphones",
    "men-oxford-shirt",
    "women-city-bag"
  ]
};
